name: deploy to azure
on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: samscoolcontainers.azurecr.io
        # From Service Account
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t samscoolcontainers.azurecr.io/dockerized:${{ github.sha }}
        docker push samscoolcontainers.azurecr.io/dockerized:${{ github.sha }}

    - uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: samscoolcluster
        resource-group: demo

    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
          resources/pod.yml
        images: |
          samscoolcontainers.azurecr.io/dockerized:${{ github.sha }}